import Link from "next/link";
import { recordRoutes, recordHref, type RecordKind } from "@/lib/records";
export type SearchGroup = { type: RecordKind; data: { id: string; title: string | null }[] | null; count: number | null; error: { message: string } | null };
export function WorkspaceSearchView({ text, kind, page, results }: { text: string; kind?: RecordKind; page: number; results: SearchGroup[] }) {
  const href = (type: string, n = 1) => `/search?${new URLSearchParams({ q: text, type, page: String(n) })}`;
  return <><header className="page-header"><div><p className="eyebrow">Across your workspace</p><h1 className="page-title">Find your research.</h1><p className="page-description">Search saved titles across references, files, notes, topics, projects, collections, and boards.</p></div><Link className="button" href="/discover">Discover external sources ↗</Link></header>
    <form className="repository-search" role="search"><label className="field"><span>Search your saved work</span><input name="q" defaultValue={text} maxLength={120} placeholder="Material, precedent, project…" required /></label><label className="field"><span>Repository</span><select name="type" defaultValue={kind || ""}><option value="">All repositories</option>{Object.entries(recordRoutes).map(([key,value]) => <option key={key} value={key}>{value.label}</option>)}</select></label><button className="button button-primary">Search</button></form>
    {!text && <div className="empty-state"><h2>Start with something you remember.</h2><p>A title, a material, or part of a project name. Search covers titles; PDF contents and semantic matching will come later.</p></div>}
    {text && results.every(group => !group.error && !group.count) && <div className="empty-state"><h2>No matching titles</h2><p>Try a shorter phrase or search all repositories.</p>{kind && <Link className="button" href={href("")}>Search all repositories</Link>}</div>}
    <div className="search-groups">{results.filter(group => group.error || group.count).map(group => <section className="usage-panel" key={group.type}><div className="section-heading"><h2>{recordRoutes[group.type].label}</h2><span className="record-meta">{group.count ?? "—"} matches</span></div>{group.error ? <p role="alert">This repository could not be searched. Please retry.</p> : <><ul className="usage-list">{group.data?.map(item => <li key={item.id}><Link href={recordHref(group.type, item.id)}><strong>{item.title || "Untitled"}</strong><span aria-hidden="true">↗</span></Link></li>)}</ul>{!kind && (group.count || 0) > 20 && <Link className="button" href={href(group.type)}>All {group.count} matches</Link>}</>}</section>)}</div>
    {kind && <nav className="section-actions" aria-label="Search pages">{page > 1 && <Link className="button" href={href(kind,page-1)}>Previous</Link>}{page*20 < (results[0]?.count || 0) && <Link className="button" href={href(kind,page+1)}>Next</Link>}</nav>}
  </>;
}
